tools:
    pylint:
        python_version: '3'
        enabled: true
        config:
            logging:
                unsupported_format: true
                format_truncated: true
                too_many_args: true
                too_few_args: true
                not_lazy: true
                enabled: true
                logging_modules: logging
            string_constant:
                backslash_in_string: true
                unicode_escape_in_string: true
            format:
                unnecessary_semicolon: true
                bad_indentation: { indentation: '4 spaces', enabled: true }
                mixed_indentation: true
                old_ne_operator: true
                lowercase_l_suffix: true
                backtick: true
                line_too_long: { max_length: '120', enabled: true }
                too_many_lines: { enabled: false, max_lines: 1000 }
                trailing_whitespace: true
                final_newline: true
                multiple_statements: true
                superfluous_parens: true
                bad_whitespace: true
                enabled: true
            type:
                no_member: true
                not_callable: true
                maybe_no_member: true
                assignment_from_no_return: true
                no_value_for_parameter: true
                too_many_function_args: true
                duplicate_keyword_arg: true
                unexpected_keyword_arg: true
                redundant_keyword_arg: true
                missing_kwoa: true
                assignment_from_none: true
                enabled: true
            variables:
                used_before_assignment: true
                undefined_variable: true
                undefined_all_variable: true
                invalid_all_object: true
                no_name_in_module: true
                global_variable_undefined: true
                global_variable_not_assigned: true
                global_statement: true
                global_at_module_level: true
                unused_import: true
                unused_variable: true
                unused_argument: true
                unused_wildcard_import: true
                redefined_outer_name: true
                redefined_builtin: true
                redefine_in_handler: true
                undefined_loop_variable: true
                unbalanced_tuple_unpacking: true
                unpacking_non_sequence: true
                enabled: true
            basic:
                init_is_generator: true
                return_in_init: true
                function_redefined: true
                not_in_loop: true
                return_outside_function: true
                yield_outside_function: true
                return_arg_in_generator: true
                nonexistent_operator: true
                duplicate_argument_name: true
                missing_reversed_argument: true
                abstract_class_instantiated: true
                bad_reversed_sequence: true
                unreachable: true
                dangerous_default_value: true
                pointless_statement: true
                pointless_string_statement: true
                expression_not_assigned: true
                unnecessary_pass: true
                unnecessary_lambda: true
                duplicate_key: true
                deprecated_lambda: false
                useless_else_on_loop: true
                old_raise_syntax: true
                exec_used: true
                eval_used: true
                bad_builtin: false
                star_args: true
                lost_exception: true
                assert_on_tuple: true
                blacklisted_names:
                    enabled: false
                    bad_names: 'foo,bar,baz,toto,tutu,tata'
                invalid_name:
                    functions: '[a-z_][a-z0-9_]{2,30}$'
                    variables: '[a-z_][a-z0-9_]{2,30}$'
                    whitelisted_names: 'i,j,k,ex,Run,_'
                    constants: '(([A-Z_][A-Z0-9_]*)|(__.*__))$'
                    attributes: '[a-z_][a-z0-9_]{2,30}$'
                    arguments: '[a-z_][a-z0-9_]{2,30}$'
                    class_attributes: '([A-Za-z_][A-Za-z0-9_]{2,30}|(__.*__))$'
                    inline_vars: '[A-Za-z_][A-Za-z0-9_]*$'
                    classes: '[A-Z_][a-zA-Z0-9]+$'
                    modules: '(([a-z_][a-z0-9_]*)|([A-Z][a-zA-Z0-9]+))$'
                    methods: '[a-z_][a-z0-9_]{2,30}$'
                    enabled: true
                missing_docstring: true
                empty_docstring: true
                missing_module_attribute: true
            miscellaneous:
                fixme: true
                invalid_encoded_data: false
            open_mode:
                bad_open_mode: true
            imports:
                wildcard_import: true
                deprecated_module: true
                relative_import: true
                reimported: true
                import_self: true
                misplaced_future: false
                cyclic_import: true
                import_error: true
            classes:
                method_hidden: true
                access_member_before_definition: true
                no_method_argument: true
                no_self_argument: true
                interface_is_not_class: true
                missing_interface_method: true
                bad_context_manager: true
                invalid_slots_object: true
                invalid_slots: true
                attribute_defined_outside_init: true
                bad_staticmethod_argument: true
                protected_access: true
                arguments_differ: true
                signature_differs: true
                abstract_method: true
                super_init_not_called: true
                no_init: true
                non_parent_init_called: true
                non_iterator_returned: true
                no_self_use: true
                bad_classmethod_argument: true
                bad_mcs_method_argument: true
                bad_mcs_classmethod_argument: true
                method_check_failed: false
                unresolved_interface: false
            design:
                too_many_ancestors: false
                too_many_instance_attributes: false
                too_few_public_methods: false
                too_many_public_methods: false
                too_many_return_statements: false
                too_many_branches: false
                too_many_arguments: false
                too_many_locals: false
                too_many_statements: false
                abstract_class_not_used: true
                abstract_class_little_used: true
                interface_not_implemented: true
            similarities:
                duplicate_code: false
            exceptions:
                bad_except_order: true
                raising_bad_type: true
                bad_exception_context: false
                raising_non_exception: true
                notimplemented_raised: true
                catching_non_exception: true
                raising_string: true
                bare_except: true
                broad_except: true
                pointless_except: true
                nonstandard_exception: false
                binary_op_exception: false
                unpacking_in_except: false
            newstyle:
                slots_on_old_class: false
                super_on_old_class: false
                bad_super_call: true
                missing_super_argument: false
                property_on_old_class: false
                old_style_class: false
            string:
                bad_format_character: true
                truncated_format_string: true
                mixed_format_string: true
                format_needs_mapping: true
                missing_format_string_key: true
                too_many_format_args: true
                too_few_format_args: true
                bad_str_strip_call: true
                bad_format_string_key: true
                unused_format_string_key: true
        plugins: {  }
        filter:
            paths: {  }
            excluded_paths: {  }
    external_code_coverage:
        enabled: true
    python_analyzer:
        enabled: true
        config:
            metrics: true
            duplication_detector:
                enabled: true
                min_mass: 25
        file_extensions:
            - .py
        filter:
            paths: {  }
            excluded_paths: {  }
build:
    environment:
        python: 3.4.1
        hosts: {  }
        variables: {  }
        mysql: false
        postgresql: false
        redis: false
        elasticsearch: false
        rabbitmq: false
        mongodb: false
        neo4j: false
        memcached: false
    dependencies:
        before: {  }
        override: {  }
        after: {  }
    tests:
        override:
            -
                command: python setup.py test
                coverage:
                    file: '.coverage'
                    format: 'py-cc'
        before: {  }
        after: {  }
    container: default
    linked_containers: {  }
    deployment: {  }
    cache:
        directories: {  }
filter:
    paths: {  }
    excluded_paths: {  }
build_failure_conditions: {  }
application:
    type: none
    cache:
        directories: {  }
    environment:
        python: 3.4.1
        hosts: {  }
        variables: {  }
        mysql: false
        postgresql: false
        redis: false
        elasticsearch: false
        rabbitmq: false
        mongodb: false
        neo4j: false
        memcached: false
