language: python
python: 3.4
before_script:
   - mkdir -p shippable/testresults
   - mkdir -p shippable/codecoverage
script:
   - py.test --junitxml=shippable/testresults/nosetests.xml test/
   - which python && py.test --cov-report xml --cov lahorie test/ && mv coverage.xml shippable/codecoverage/
after_script:
   - pip install scrutinizer-ocular
   - ocular --access-token "your-token" --data-file "coverage.xml" --config-file ".coveragerc"